// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARW5yV44i5PGv4f-5Is2hr6UJmBqGossM',
    appId: '1:558147196175:web:773763bf658cf113fb1a7a',
    messagingSenderId: '558147196175',
    projectId: 'kin-rai-dee-65223',
    authDomain: 'kin-rai-dee-65223.firebaseapp.com',
    storageBucket: 'kin-rai-dee-65223.firebasestorage.app',
    measurementId: 'G-TGWV61WPX6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp051fm70Hbxx9bkvxefWqvR-6Fc_F4zE',
    appId: '1:558147196175:android:3f9134608bfa8320fb1a7a',
    messagingSenderId: '558147196175',
    projectId: 'kin-rai-dee-65223',
    storageBucket: 'kin-rai-dee-65223.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPy19ijBVcF4sahQn93esLGoQJOKzHRn0',
    appId: '1:558147196175:ios:86f0e3b778e2aa62fb1a7a',
    messagingSenderId: '558147196175',
    projectId: 'kin-rai-dee-65223',
    storageBucket: 'kin-rai-dee-65223.firebasestorage.app',
    iosBundleId: 'com.example.kinRaiDee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPy19ijBVcF4sahQn93esLGoQJOKzHRn0',
    appId: '1:558147196175:ios:86f0e3b778e2aa62fb1a7a',
    messagingSenderId: '558147196175',
    projectId: 'kin-rai-dee-65223',
    storageBucket: 'kin-rai-dee-65223.firebasestorage.app',
    iosBundleId: 'com.example.kinRaiDee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARW5yV44i5PGv4f-5Is2hr6UJmBqGossM',
    appId: '1:558147196175:web:aba7eb7d0ac98f12fb1a7a',
    messagingSenderId: '558147196175',
    projectId: 'kin-rai-dee-65223',
    authDomain: 'kin-rai-dee-65223.firebaseapp.com',
    storageBucket: 'kin-rai-dee-65223.firebasestorage.app',
    measurementId: 'G-WMWQ7W55FL',
  );
}
